### ISSUE TITLE
Warnings when the same ingredient is selected

### ISSUE THREAD

**Issue by EduardoGiacomini** [EduardoGiacomini/Vue.js-Burger-Builder#2]
### Description
There are some warnings when I select or unselect the same ingredient... I think the problem is with the `key` property.

<img width="790" alt="Screen Shot 2022-03-02 at 22 44 36" src="https://user-images.githubusercontent.com/31314944/156486703-a8a5e5fa-522f-45ea-bf03-4a4702ecefc5.png">

**Comment by ajukadavid** [comment]
can I work on this issue?

**Comment by EduardoGiacomini** [comment]
Hello Ajuka David, how are you?

So, I just closed the issue with this commit (
https://github.com/EduardoGiacomini/Vue.js-Burger-Builder/commit/105cb3b5ec8d08874f426ad880e3658fa9b19136
) 😅.

I am so sorry.

If you are able to help me we can find other tasks to do.

Happy coding, Carlos Giacomini.

Em qui., 3 de mar. de 2022 às 22:48, Ajuka David ***@***.***>
escreveu:
